version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: cf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: furniture
    ports:
      - "3306:3306"
  mongo:
    image: mongo:7
    container_name: cf-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
